import { Header } from "@/shared/components/shared";
import { Metadata } from "next";
import { Container } from "@/shared/components/shared/container";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Next Pizza || Checkout",
  description: "Generated by create next app",
};

export default function CheckoutLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <main className="min-h-screen bg-[#F4F1EE]">
      <Container>
        <Suspense>
          <Header
            hasSearch={false}
            hasCart={false}
            className="border-gray-200"
          />
        </Suspense>
        {children}
      </Container>
    </main>
  );
}
